name: ExcellentEnchants
main: su.nightexpress.excellentenchants.ExcellentEnchants
version: 1.0.0-TechBedrock
api-version: "1.19"
authors: [ NightExpress, Nailm, g2213swo ]
description: Vanilla-like enchants for your server.
dependencies:
  server:
    NexEngine:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    NoCheatPlus:
      load: OMIT
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: OMIT
      required: false
      join-classpath: true
    CustomFishing:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  excellentenchants.admin:
    description: Grants access to all plugin functions.
    default: op
    children:
      excellentenchants.user: true
      excellentenchants.command: true
  excellentenchants.user:
    description: Grants access to basic player plugin functions.
    default: op
  excellentenchants.command:
    description: Grants access to all the plugin commands.
    default: op
    children:
      excellentenchants.command.book: true
      excellentenchants.command.enchant: true
      excellentenchants.command.list: true
      excellentenchants.command.tierbook: true
  excellentenchants.command.book:
    description: Grants access to /eenchants book command.
    default: op
  excellentenchants.command.enchant:
    description: Grants access to /eenchants enchant command.
    default: op
  excellentenchants.command.list:
    description: Grants access to /eenchants list command.
    default: op
  excellentenchants.command.tierbook:
    description: Grants access to /eenchants tierbook command.
    default: op