/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("su.nightexpress.excellentenchants.java-conventions")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT")
}

description = "NMS"
